### ISSUE TITLE
Cannot decompress the .rar folder of the dataset "the archive is either in unknown format or damaged" 

### ISSUE THREAD

**Issue by TinhinaneMEZAIR** [airtlab/A-Dataset-for-Automatic-Violence-Detection-in-Videos#1]
Hello,
I Cannot decompress the .rar folder of the dataset "the archive is either in unknown format or damaged" 
Could you help me download and open the dataset please
Kind regards,

**Comment by msmshubber** [comment]
I faced same problem and solved it by downloading the dataset using ssh instead of https

**Comment by airtl** [comment]
Hi, there is no ".rar" archive in the dataset, therefore cloning the repository with "git clone" instead of downloading it as an archive should work.
